# Generated by Django 4.2.7 on 2023-11-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItmoIdProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isu', models.PositiveIntegerField(blank=True, null=True, verbose_name='ИСУ')),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс')),
                ('faculty', models.CharField(blank=True, max_length=50, verbose_name='Факультет')),
                ('group', models.CharField(blank=True, max_length=7, verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'профиль ITMO.ID',
                'verbose_name_plural': 'профили ITMO.ID',
                'db_table': 'itmo_id_profile',
            },
        ),
    ]
