# Generated by Django 4.2.7 on 2023-11-06 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adapter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'факультет',
                'verbose_name_plural': 'факультеты',
                'db_table': 'survey_faculty',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.TextField(choices=[('text_area', 'TextArea'), ('adapter_slider', 'AdapterSlider'), ('slider', 'Slider'), ('select', 'Select'), ('training_select', 'TrainingSelect')], max_length=15, verbose_name='Виджет')),
                ('text', models.CharField(max_length=200, verbose_name='Основной текст')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='Дополнительный текст')),
                ('training_text', models.CharField(blank=True, max_length=200, verbose_name='Основной текст')),
                ('training_help_text', models.CharField(blank=True, max_length=200, verbose_name='Дополнительный текст')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'db_table': 'survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='Название')),
                ('students_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество студентов')),
                ('adapters', models.ManyToManyField(blank=True, related_name='groups', to='adapter.adapter', verbose_name='Адаптеры')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'db_table': 'survey_group',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='Ответ')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Балл')),
                ('adapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adapter.adapter', verbose_name='Адаптер')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveyquestion', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
                'db_table': 'survey_answer',
            },
        ),
    ]
