# Generated by Django 4.2.7 on 2023-11-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='component',
            field=models.CharField(choices=[('text_area', 'TextArea'), ('adapter_slider', 'AdapterSlider'), ('slider', 'Slider'), ('select', 'Select'), ('training_select', 'TrainingSelect')], max_length=15, verbose_name='Виджет'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='training_help_text',
            field=models.CharField(blank=True, help_text='Используется для слайдера в TrainingSelect виджете', max_length=200, verbose_name='Второй дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='training_text',
            field=models.CharField(blank=True, help_text='Используется для слайдера в TrainingSelect виджете', max_length=200, verbose_name='Второй основной текст'),
        ),
    ]
